### PR TITLE
Additional argument for tp.file.move for passing down specific files.

### LINKED ISSUE #341: tp.file.move is not working correctly
**Plugin informations (please complete the following information):**
 - OS: PopOS!
 - Templater version: 1.8.1
 - Obsidian version: v0.12.12 (Installer v0.12.10)
 - Templater settings: Default

**Describe the bug**
move(A/B) works but move(A/B/C) or more levels does not work

**Expected behavior**
File Should move

### PR DESCRIPTION
**Pull request by alchemistake**
# What
This adds an additional optional parameter for moving any `TFile` inside the vault. With this edit, existing user templates does not break since parameter is optional and It gives more flexibility if some people want to pass down a file explicitly.

# Why
I had a problem with `tp.file.move()` because of `this.config.target_file` being different in the different scopes of my template. 

For example:
```
<%
tp.file.create_new("", "a_file_I_dont_want_to_move);
console.log(this.config.target_file);
tp.file.move("new_location/my_file");
%>
```
This code snippet moves the newly generated file rather than the file I triggered the template with. Console log outputs the file I want to move a.k.a. active_file.

Also updated the doc to have the optional parameter, if it is not clear I can add more details there.

closes #341

### CODE REVIEW

**Comment by shabegom** [comment]
@alchemistake can you resolve the merge conflicts and I will merge this

**Comment by alchemistake** [comment]
> @alchemistake can you resolve the merge conflicts and I will merge this

I think i added more stuff on this branch later. Ill fix it in weekend

**Comment by alchemistake** [comment]
Hi @shabegom ! I just fixed the conflicts. Do you need me to anything else?

**Comment by shabegom** [comment]
Looks good. Assuming you've tested this and:

- it functions as expected
- it doesn't break if the arg isn't included

It shouldn't work on mobile in general so that's fine.

I'll merge tomorrow morning and cut a release.

**Pull request merged**
