### PR TITLE
Add option to use regex on file path instead of folder templates

### PR DESCRIPTION
**Pull request by harmtemolder**
As discussed in #471 the current folder templates do not cover all use cases. Having the option to use regex on the file path of a new file instead should give advanced users the flexibility they seek.

I've kept the folder templates option intact, letting a user pick between the two. Their toggles are linked, so enabling one will disable the other.

I've also updated the docs to match the current layout of the settings window.

And I made two minor changes to `.gitignore`:
- Exclude `package-lock.json`, because I don't think we need to lock versions, do we?
- Include `.vscode/settings.json`, to allow for synching of workspace settings between our VSCodes, specifically `editor.defaultFormatter`, so that all of use Prettier (and thus the included `.prettierrc.json`)

### CODE REVIEW

**Comment by harmtemolder** [comment]
n=1 of course, but I've been using these changes without any hick-ups since December

**Comment by quanru** [comment]
Is it possible to merge with the main branch?

**Comment by harmtemolder** [comment]
> Is it possible to merge with the main branch?

We would need @SilentVoid13 for that

**Comment by AB1908** [comment]
> Exclude package.json, because I don't think we need to lock versions, do we?

We still actually. It's still useful to pin APIs to specific obsidian versions. There's also scripts and dependencies in there that we'd like to start updated. Finally I think Obsidian itself needs the version info in it to install properly.

**Comment by quanru** [comment]
Could you remove the changes to .gitignore and vscode configuration, or have a separate MR, so that this feature can be merged faster? @harmtemolder

**Comment by harmtemolder** [comment]
Sorry about that. I see that I wrote `package.json`, but I actually excluded `package-lock.json`, not `package.json`. I'll remove `.vscode/settings.json`

**Comment by SINC-G** [comment]
Excuse me, Does the PR have made any new progress?

**Comment by harmtemolder** [comment]
The PR was finished a year ago, but I see there are now conflicts because of changes made to the plugin in the time since then. I (or someone else) would need to resolve those before @SilentVoid13 would be able to merge the PR.

@SilentVoid13 Are you interested in merging this PR? If so, I'll take the time to resolve the conflicts

**Comment by Zachatoo** [comment]
I am interested in seeing this functionality added. If you resolve the conflicts and remove the unrelated changes (such as updating the `.gitignore` file) then I will be happy to pull this down to test and merge it if it works on my end.

Ideally, we'd also add unit tests for this, but I don't think it's strictly required, as long as the existing tests still pass.

**Comment by harmtemolder** [comment]
@Zachatoo I've solved all conflicts, built and tested with the file regex templates I use in my vault. Those work as expected. Could you explicitly test that this does not break any existing folder templates somebody might be using?

I've never written unit tests in TypeScript, but adding those for this functionality sounds like a good idea. Let me know how I can help with that.

**Review by Zachatoo — APPROVED** [review]
@harmtemolder Thanks for making those changes! PR looks a lot cleaner. Automated tests are passing and existing folder templates functionality appears to be working still.

There were some changes from #1468 that will result in a UX conflict, but I can resolve that after I merge this before the release.

**Pull request merged**
