### PR TITLE
Fix PromptModal default value needs to be set to this.value on load

### PR DESCRIPTION
**Pull request by GitMurf**
Issue where it is undefined if you just accept the default string. Happens with all combo of options multi line true/false... error throw true/false. See video.

https://user-images.githubusercontent.com/64155612/189000550-c201fb6c-01ed-4d26-8a9f-eab062308a72.mp4

### CODE REVIEW

**Comment by GitMurf** [comment]
@shabegom I will refactor the code a bit as discussed in Discord to simplify it instead of using the `onchange` but wanted to fix the bug first. Let me know if you have any questions. I tested against all my scenarios that were breaking and they all work now.

**Review by shabegom — APPROVED** [review]
LGTM

**Comment by shabegom** [comment]
@GitMurf for future PRs, please follow conventional commits spec:https://conventionalcommits.org/

**Comment by GitMurf** [comment]
@shabegom just so i’m clear, my commit message was fine except needed to add a “:” colon and make Fix lowercase? Anything else?

**Pull request merged**
