### PR TITLE
Added title image internal template

### PR DESCRIPTION
**Pull request by silentdot**
Hey, 

Added a new internal template to get an image based on the current note title. Also edited the Readme to include the new template and edited the description for the random image templater

### CODE REVIEW

**Comment by silentdot** [comment]
Also edited the old random image template to only use horizional pictures

**Comment by SilentVoid13** [comment]
Looks great, thanks for the contribution ! 
Just a question: any reason you use `https://source.unsplash.com/featured` instead of `https://source.unsplash.com/random` (what's the difference) ?

**Comment by silentdot** [comment]
> Looks great, thanks for the contribution ! 
> 
> Just a question: any reason you use `https://source.unsplash.com/featured` instead of `https://source.unsplash.com/random` (what's the difference) ?

The difference is, featured is the official collection of fotos and those can be searched. Using featured made my keyword request more accurate.
Random selects a random image from the whole Unsplash Database.

More info: https://source.unsplash.com

**Comment by SilentVoid13** [comment]
I see !

**Comment by Mpic** [comment]
Any idea how to automatically download, store in attachments and use the downloaded image instead of relying on the web link ?

**Comment by Mpic** [comment]
> 
> 
> Any idea how to automatically download, store in attachments and use the downloaded image instead of relying on the web link ?

I found a solution but it uses absolute path : 

```
echo ![[{{note_title}}-weather.png]]
curl -s -H "Accept-Language: fr" http://wttr.in/Liege_2tp.png --output <absolute-path-to-obsidian-attachments>/{{note_title}}-weather.png
```

**Pull request merged**
